- name: Install Java
  package:
    name: java
    state: present

- name: Create Application User
  user:
    name: "{{APP_USER}}"

- name: Download Tomcat
  unarchive:
   src: "{{TOMCAT_URL}}"
   dest: "{{APP_HOME}}"
   remote_src: yes 
  become_user: "{{APP_USER}}"

- name: Download WAR File
  get_url:
   url: "{{WAR_URL}}"
   dest: "{{TOMCAT_HOME}}/webapps/student.war"
  become_user: "{{APP_USER}}"
  