- name: Install Java
  package:
    name: java
    state: present

- name: Create Application User
  user:
    name: "{{APP_USER}}"

- name: Download Tomcat
  unarchive:
   src: "{{TOMCAT_URL}}"
   dest: "{{APP_HOME}}"
   remote_src: yes 
  become_user: "{{APP_USER}}"

- name: Download WAR File
  get_url:
   url: "{{WAR_URL}}"
   dest: "{{TOMCAT_HOME}}/webapps/student.war"
  become_user: "{{APP_USER}}"

- name: Download JDBC Jar File
  get-url:
   url: "{{JDBC_URL}}"
   dest: "{{TOMCAT_HOME}}/lib/mysql-connector.jar"
  become_user: "{{APP_USER}}"

- name: Copy context.xml file
  template:
    src: context.xml.j2
    dest: "{{TOMCAT_HOME}}/conf/context.xml"
  become_user: "{{APP_USER}}"



