- name: Update ubuntu repos
  shell: apt-get update

- name: Install Java
  apt:
   name: openjdk-8-jdk
   state: present

- name: Create Application User
  user: 
   name: "{{APP_USER}}"

- name: Dowmload Tomcat
  unarchive:
   src: "{{TOMCAT_URL}}"
   dest: "{{APP_HOME}}"
   remote_src: yes
  become_user: "{{APP_USER}}"