- name: Install httpd
  hosts: all
  tasks:
   - name: Install httpd
     package:
      name: httpd
      state: present

   - name: Start httpd
     service:
      name: httpd
      state: started

   - name: Stop htppd
     service:
      name: httpd
      state: stopped