- name: Prnit variable from shell command
  hosts: all
  tasks:
   - name: Register variable
     shell: uptime
     register: me 

   - name: Print me variable
     debug:
       msg: "{{me.stdout}}"
  
