- name: Print gather facts variables
  hosts: all
  #gather_facts: no
  tasks:
   - name: Print default facts
     debug:
       msg: "{{ansible_distribution}}"
       msg: "{{ansible_architecture}}"
#  - name: Print custom fact
#    debug:
#      msg: "{{ansible_local.demo.URL}}"
       
