- name: Checking variable precedence
  hosts: all
  #vars: 
   #URL: vars.from.play.com
  tasks:
   - name: Print a variable from anywhere
     debug:
       msg: "{{URL}}"
     #vars:
      #URL: vars.from.task.com
  