- name: Demo on ignore condition
  hosts: all
  tasks:
   - name: Check dpkg command is there or not
     shell: which dpkg
     register: out
     ignore_errors: yes

   - name: find kernel dpkg version
     shell: dpkg --list | grep kernel
     when: out.rc == 0
