- name: Demo on tags
  hosts: all
  gather_facts: no
  tasks:
   - name: Print one if tag one is given
     debug:
       msg: one
     tags:
      - one

   - name: Print two if tag two is given
     debug:
       msg: Two
     tags:
      - two

   - name: Print three if tag three is given
     debug:
       msg: Three
     tags: 
      - three

