- name: Demo on loops
  hosts: all
  tasks:
   - name: Print multiple names
     debug: 
       msg: "Hello {{item}}"
     loop:
      - Anoop
      - Kumar
      - Anoop Kumar
   
   - name: Have two lists as loop
     debug: 
       msg: "Hello {{item[0]}}, & Hello {{item[1]}}"
     loop:
      - ["One", "Two"]
      - ["New", "Old"]
      