- name: Demo on filters
  hosts: all
  tasks: 
   - name: Get load average
     shell: uptime
     register: out

   - name: Print load value
     set_fact:
      #LOAD: "{{out.stdout.split()[-3].split('.')[0]}}"
      LOAD: "6"

   - name: Send email of load average 
     shell: curl -s --user 'api:a2ff99eb1378107de85386f630ce2077-5645b1f9-a580b529' \
                https://api.mailgun.net/v3/sandboxe53c4332ae8e49638e46147ca5f9c5d4.mailgun.org \
                -F from='LOAD AVERAGE NOTIFY <anoopkumarnasarapu@gmail.com>' \ 
                -F to=rickywilsoncentillionz@gmail.com \
                -F subject='LOAD AVERAGE' \
                -F text="Load Average is High on Server"
     when: LOAD > "5"
