- name: Demo on filters
  hosts: all
  tasks: 
   - name: Get load average
     shell: uptime
     register: out

   - name: Print load value
     debug:
       msg: "{{out.stdout.split()[-3].split('.')[0]}}"